# .air.toml
root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o tmp/main ./cmd"
bin = "tmp/main"
full_bin = ""
delay = 1000
log = "stdout"
include_ext = ["go"]
exclude_dir = ["tmp", "frontend", "node_modules"]

[log]
time = true
