services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:3000
    volumes:
      - ./:/app

    frontend:
      build:
        context: ./frontend
      ports:
        - "3000:3000"
      volumes:
        - ./frontend:/app
